import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

export default function Home() {
  return (
    <>
      <Head>
        <title>Binance</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="keywords" content="Blockchain Crypto Exchange, Cryptocurrency Exchange, Bitcoin Trading, Ethereum price trend, BNB, CZ, BTC price, ETH wallet registration, LTC price, Binance, Poloniex, Bittrex" data-shuvi-head="true"></meta>
        <meta name="description" content="Binance USDT Limit" data-shuvi-head="true"></meta>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="font-sans space-x-6">
        <div className="bg-[#FAFAFA]">
          <nav className="container mx-auto p-2">
            <div className="flex justify-between items-center"> 
              <Image src={"/images/logo.png"} alt="logo" width={120} height={40}/>       
              <div className="space-x-6 md:flex items-center ">
                <Link className="hidden hover:text-binance md:flex" href="/">Log In</Link>
                <Link className="bg-binance text-sm rounded-md px-3 py-2" href="/">Register</Link>
              </div>
            </div>
          </nav>
          <div className="w-[100%] h-10 md:h-8 bg-binanceLight">
            <p className="text-left text-sm md:text-md md:text-center">Register now and get verified - Enjoy Welcome Rewards up to $100!</p>
          </div>
          <div className="container flex flex-row">
            <div className="hidden text-3xl w-36 h-4 my-4 font-semibold md:flex"></div>
            <h1 className="hidden text-3xl my-4 font-semibold md:flex">Binance Blog</h1>
          </div>
        </div>
        <div className="flex flex-col md:flex-row md:justify-around">
        <div className="hidden text-3xl w-32 h-4 my-4 font-semibold md:flex"></div>
          <div className="md:flex-auto w-[100%] md:w-72 overflow-hidden"> 

            <h1 className="text-2xl mt-6 font-bold mb-2">Binance Implements $15,000 USDT Limit on First-time Transactions via Internal E-Wallet Payment</h1>
            <span className="text-md font-semibold">2024-05-08 17:54:21</span>

            <br/>     
            
            <div className="mt-6 pr-6 space-y-6">
              <p>Binance, a leading cryptocurrency trading platform, has recently introduced a new policy that imposes a $15,000 USDT limit on all first-time transactions when trading through the internal e-wallet payment system. This measure is designed to enhance security measures and protect user funds on the platform</p>
              <p>Users are advised to take note of this limit and plan their transactions accordingly to ensure compliance with the new policy. Binance encourages users to familiarize themselves with the terms and conditions associated with this limit to facilitate a seamless trading experience.</p>
            </div>
          
            <div className="my-10 space-y-6 pr-4">
             
              <Image className="" src={"/images/f5348b75-38fc-4804-8e45-85897519a96e.png"} alt="logo" width={792} height={198}/>
            </div>

            <div className="my-10 space-y-6 pr-4">
              
              <p>The platform remains committed to providing a secure and efficient trading environment for its users, prioritizing user safety and security. By implementing this limit, Binance aims to further safeguard user funds and enhance the overall trading experience for its customers.</p>
              <p>Stay updated on further announcements and developments from Bybit as we continue to strive for excellence in the cryptocurrency trading industry. Thank you for your cooperation as we work together to create a safe and secure trading environment for all users on Binance.</p>
             <p>You can contact our support for more info: <span className='text-binance text-lg font-bold'><Link href={'/'}>Binance Support</Link> </span></p>
             
            </div>
            
            <div className="my-10 space-y-6 pr-4">
             
            
              <Image src={"/images/f5348b75-38fc-4804-8e45-85897519a96e.png"} alt="logo" width={792} height={198}/>
            </div>
            

            <div className="pr-4 mb-10">
              <span className="font-bold">Disclaimer: </span><i>Your use of Binance P2P services and all information and other content (including that of third parties) included are accessible from Binance P2P services . Our only responsibility is to handle crypto transactions. </i>
            </div>

          </div>
          <div className="md:flex-1 md:w-32">
    
          </div>
          
        </div>
      </main>
    </>
  )
}
